import { type VenueId } from '@/content/venues';

import type { Activity } from '@/types/festival';

/**
 * A programação da edição 2024 — 20 atividades.
 *
 * Título, release, ficha técnica e observação são **acervo em pt-BR**,
 * transcritos do programa impresso sem alteração de grafia, ordem ou pontuação.
 * Frente, classificação e recursos de acessibilidade são chaves traduzidas.
 *
 * Cada sessão é uma atividade: "O Corpo Que Eu Habito" aparece duas vezes
 * porque foi apresentado em dois dias, como o programa o lista.
 *
 * As capas são extrações de baixa resolução do programa impresso — nenhuma
 * passa de 270px de largura. É o que `isLowResolution` registra, e é por isso
 * que nenhuma delas é apresentada em largura de viewport.
 */
interface FestivalActivity extends Activity {
  readonly venueId: VenueId;
}

const IMAGE_BASE = '/imagens/2024';

/** Capa de espetáculo extraída do programa impresso de 2024. */
function cover(file: string, altKey: string) {
  return {
    src: `${IMAGE_BASE}/${file}`,
    altKey,
    provenance: 'programa-impresso-2024',
    isLowResolution: true,
  } as const;
}

export const activities: readonly FestivalActivity[] = [
  {
    id: 'lenda',
    title: 'A Lenda de Um Homem Sem Nome',
    strand: 'mostra-oficial',
    startsAt: '2024-10-13T19:30:00-03:00',
    durationInMinutes: 50,
    venueId: 'sesi',
    company: 'Grupo Teatral Gota, Pó e Poeira',
    stateCode: 'ES',
    author: 'Adelpho Poli Monjardim e Carlos Ola',
    director: 'Carlos Ola',
    rating: 'livre',
    release:
      'O espetáculo conta a história de um homem sem nome, um velho sovina e interesseiro que oculta um passado misterioso com forças sobrenaturais. Para ver sua propriedade novamente bem e com dinheiro no bolso, o “homem sem nome” refaz um pacto que pode custar a vida de Toninho, o seu filho. E é Sebastião, o empregado da propriedade, quem pode mudar o rumo dessa história com ajuda de um santo. A peça é uma adaptação da lenda capixaba A Pedra do Diabo, que fica no bairro de Inhanguetá, em Vitória.',
    technicalSheet: [
      { label: 'Autor', value: 'Adelpho Poli Monjardim e Carlos Ola' },
      { label: 'Direção', value: 'Carlos Ola' },
      { label: 'Sonoplastia', value: 'O grupo' },
    ],
    note: 'Abertura oficial do festival às 19h.',
    accessibility: [],
    image: cover('lenda-homem-sem-nome.png', 'lenda'),
  },
  {
    id: 'violeta',
    title: 'Violeta de Los Andes',
    strand: 'mostra-oficial',
    startsAt: '2024-10-14T19:30:00-03:00',
    durationInMinutes: 55,
    venueId: 'sesi',
    company: 'Tarahumaras',
    stateCode: 'ES',
    author: 'Wilson Coelho',
    director: 'Wilson Coelho',
    rating: '14',
    release:
      'O espetáculo “Violeta de los Andes” é um monólogo teatral baseado na vida e obra de Violeta Parra (Chile, 1917-1967), multiartista identificada como precursora da Nova Canção Chilena. Violeta percorreu seu país durante 15 anos, registrando as canções populares e compôs cerca de 200 músicas, incluindo “Volver a Los 17”. A obra mostra a poeta, compositora, ceramista, pintora e bordadeira, engajada, falando de seus sonhos, amores e sofrimentos, e é recheado de seus poemas, cartas e textos.',
    technicalSheet: [
      { label: 'Texto, encenação e iluminação', value: 'Wilson Coelho' },
      { label: 'Atuação', value: 'Natalia Omena' },
      { label: 'Cenografia', value: 'Tião Fonseca' },
      { label: 'Figurino', value: 'Tarahumaras' },
      { label: 'Sonoplastia', value: 'Matheus Rezende' },
      { label: 'Arte digital', value: 'Max Goldner' },
    ],
    note: null,
    accessibility: [],
    image: cover('violeta-los-andes.png', 'violeta'),
  },
  {
    id: 'corpus',
    title: 'Corpus Em Vidas',
    strand: 'mostra-oficial',
    startsAt: '2024-10-15T19:00:00-03:00',
    durationInMinutes: 100,
    venueId: 'milson',
    company: 'Grupo de Teatro Experimental Capixaba',
    stateCode: 'ES',
    author: 'Cesar Huapaya',
    director: 'Cesar Huapaya',
    rating: 'livre',
    release:
      'Um espetáculo inovador que combina teatro-instalação, música, dança e práticas performativas. Esta obra é muito mais do que uma peça teatral; é uma experiência antropológica da performance, abrindo as portas para um diálogo necessário e impactante. “Corpus em Vidas” mergulha nas questões mais urgentes do século XXI: por que continuamos a criar corpos sem vida, torturados, vendidos, prostituídos, explorados e escravizados? Este espetáculo busca não apenas questionar, mas também oferecer propostas de um "corpus com vidas" de forma decolonial.',
    technicalSheet: [
      {
        label: 'Performers',
        value:
          'Amanda Chabudé, Amélia Barretto, Billh Bantu (Manuel Bem-vindo Soluelo), Carlos Roberto, Claudino Danilo dos Anjos, Eliezer de Almeida, Elídio Netto, Suely Bispo, Xis Makeda',
      },
      { label: 'Participação especial', value: 'Rosi Andrade' },
      { label: 'Direção', value: 'Renan e Dayse Marciel' },
      {
        label: 'Realização',
        value:
          'Grupo de Teatro Experimental Capixaba e Núcleo de Performance e Antropologia Teatral (CNPq/UFES)',
      },
    ],
    note: null,
    accessibility: [],
    image: cover('corpus-em-vidas.png', 'corpus'),
  },
  {
    id: 'olhos',
    title: 'Meus Olhos Verdes',
    strand: 'mostra-oficial',
    startsAt: '2024-10-15T20:00:00-03:00',
    durationInMinutes: 60,
    venueId: 'casa',
    company: 'Cia Teatral JC',
    stateCode: 'ES',
    author: 'José Celso Cavalieri',
    director: 'José Celso Cavalieri',
    rating: '16',
    release:
      'Alex, um garoto de programa, vive o auge de sua vida. Em meio ao luxo e às ilusões de uma realidade construída para agradar aos outros, ele parece estar no controle de tudo. Porém, quando o passado ressurge em sua vida, trazendo consigo segredos e traumas que ele acreditava estarem enterrados, sua existência começa a se desintegrar. A trama coloca em xeque a própria noção de verdade, memória e identidade.',
    technicalSheet: [
      { label: 'Texto e direção', value: 'José Celso Cavalieri' },
      { label: 'Elenco', value: 'Diego Pianna' },
      { label: 'Cenografia', value: 'Diego Pianna, Felipe Avide e José Celso Cavalieri' },
      { label: 'Figurino', value: 'Diego Pianna' },
      { label: 'Iluminação', value: 'José Celso Cavalieri' },
      { label: 'Sonoplastia', value: 'Felipe Avide' },
      { label: 'Realização', value: 'Cia Teatral JC' },
    ],
    note: null,
    accessibility: [],
    image: cover('meus-olhos-verdes.png', 'olhos'),
  },
  {
    id: 'corpo16',
    title: 'O Corpo Que Eu Habito',
    strand: 'mostra-oficial',
    startsAt: '2024-10-16T19:30:00-03:00',
    durationInMinutes: 55,
    venueId: 'casa',
    company: 'Cia Da Ideia — Companhia de Dança',
    stateCode: 'RJ',
    author: 'Sueli Guerra',
    director: 'Sueli Guerra e Alessandro Brandão',
    rating: 'livre',
    release:
      'Um espetáculo híbrido em que dança, teatro, música e performance se mesclam com o objetivo de promover uma reflexão sobre o corpo de cada indivíduo no aqui e agora. No espetáculo, cada artista / intérprete traz para o palco suas experiências, histórias e particularidades, explorando as possibilidades e potencialidades de seus corpos. Em cena, 7 bailarinos compõem seus solos que acabam por se tangenciar formando duos, trios e momentos de encenação coletiva.',
    technicalSheet: [
      { label: 'Idealização', value: 'Sueli Guerra' },
      {
        label: 'Pesquisa, concepção e direção artística',
        value: 'Sueli Guerra e Alessandro Brandão',
      },
      {
        label: 'Intérpretes criadores',
        value:
          'Sueli Guerra, Alessandro Brandão, Daniel Chagas / Jefferson Almeida, Edney D’conti, Andreia Pimentel, Renata Reinheimer e Saulo Eduardo',
      },
      { label: 'Musicista', value: 'Ana Paula Cruz' },
      { label: 'Trilha sonora original', value: 'Rodrigo Russano' },
      { label: 'Cenografia', value: 'Gisele Batalha' },
      { label: 'Figurinos', value: 'Patrícia Muniz' },
      { label: 'Iluminação', value: 'Paulo Cesar Medeiros' },
      { label: 'Produção local', value: 'Lalau Martins' },
      { label: 'Direção de produção', value: 'Cacau Gondomar' },
      { label: 'Realização', value: 'CLG — Canteiro de Ideias e Cia da Ideia' },
    ],
    note: 'Patrocínio Instituto Cultural Vale, via Lei Federal de Incentivo à Cultura / Lei Rouanet.',
    accessibility: ['signLanguage', 'audioDescription'],
    image: cover('corpo-que-eu-habito.png', 'corpo'),
  },
  {
    id: 'corpo17',
    title: 'O Corpo Que Eu Habito',
    strand: 'mostra-oficial',
    startsAt: '2024-10-17T19:30:00-03:00',
    durationInMinutes: 55,
    venueId: 'casa',
    company: 'Cia Da Ideia — Companhia de Dança',
    stateCode: 'RJ',
    author: 'Sueli Guerra',
    director: 'Sueli Guerra e Alessandro Brandão',
    rating: 'livre',
    release:
      'Segunda apresentação do espetáculo híbrido em que dança, teatro, música e performance se mesclam para promover uma reflexão sobre o corpo de cada indivíduo no aqui e agora.',
    technicalSheet: [
      { label: 'Idealização', value: 'Sueli Guerra' },
      { label: 'Direção', value: 'Sueli Guerra e Alessandro Brandão' },
      { label: 'Realização', value: 'CLG — Canteiro de Ideias e Cia da Ideia' },
    ],
    note: null,
    accessibility: ['signLanguage', 'audioDescription'],
    image: cover('corpo-que-eu-habito-2.png', 'corpo2'),
  },
  {
    id: 'charanga',
    title: 'A Charanga dos Proscritos',
    strand: 'mostra-oficial',
    startsAt: '2024-10-17T19:30:00-03:00',
    durationInMinutes: 60,
    venueId: 'praca',
    company: 'Boyásha Trupe de Teatro',
    stateCode: 'ES',
    author: 'George Orwell',
    director: 'João Paulo Stein',
    rating: 'livre',
    release:
      'Um bando. Uma trupe. Uma charanga! Perambulando de lá para cá. Tocando fanfarras. Penúria... O Destemido! Outra charanga. Fusca 1975 em quase perfeito estado de conservação. Numa granja, em algum tempo, um humano explorador chafurda na força de trabalho de um bando de animais. Fartos da exploração os animais se rebelam e expulsam o opressor. Mas tudo está melhor... é o que afirma Garganta, o portavoz do poder. Expulsos, os proscritos levantam acampamento. Penúria parte. Mas a Charanga resiste!',
    technicalSheet: [
      { label: 'Texto original', value: 'George Orwell (1903-1950)' },
      { label: 'Adaptação e dramaturgia', value: 'Márcio Marciano e Boyásha' },
      { label: 'Elenco', value: 'João Paulo Stein e Murilo Iglesias' },
      { label: 'Direção', value: 'João Paulo Stein' },
      { label: 'Direção musical', value: 'Murilo Iglesias' },
      { label: 'Direção de texto e preparação vocal', value: 'Babaya Morais' },
      { label: 'Colaboração artística', value: 'Lydia Del Picchia e Luiz Rocha' },
      { label: 'Cenário e figurino', value: 'Boyásha' },
      { label: 'Assistência de palco', value: 'Patrick Benevides' },
    ],
    note: null,
    accessibility: [],
    image: cover('charanga-dos-proscritos.png', 'charanga'),
  },
  {
    id: 'dona',
    title: 'Dona Rua Gentileza, Educando Hoje Os Motoristas de Amanhã',
    strand: 'mostra-oficial',
    startsAt: '2024-10-18T14:00:00-03:00',
    durationInMinutes: 50,
    venueId: 'casa',
    company: 'Trupe Ratimbum',
    stateCode: 'ES',
    author: 'Taty Moraes',
    director: 'Elenice Moreira',
    rating: null,
    release:
      'A peça conta a estória da personagem Emília, que sai do interior em direção à cidade grande, onde pretende conhecer mais sobre a Educação no Trânsito, para ensinar onde mora. Chegando à cidade conhece o guarda Prudêncio, que a acompanha em sua trajetória, ensinando as regras do trânsito. Juntos, encontram a personagem principal, dona Rua Gentileza, que fica aborrecida toda vez que um motorista joga lixo pela janela do carro. O espetáculo tem músicas próprias e passa por situações como faixa de pedestre, rotatória, caixa amarela, sinalização, ônibus escolar e informações sobre Leis de Trânsito.',
    technicalSheet: [
      { label: 'Autor e direção', value: 'Taty Moraes e Elenice Moreira' },
      {
        label: 'Elenco',
        value: 'Cristina Moreira, Anna Mark, Ary Ottis, Ramon Bastos e Everton de Souza',
      },
      { label: 'Produção executiva', value: 'Taty Moraes' },
      { label: 'Produção', value: 'Elenice Moreira' },
      { label: 'Assistente de produção', value: 'Nívea Bromate' },
      { label: 'Montagem e contrarregra', value: 'Walter Gomes' },
      { label: 'Sonoplastia', value: 'Beré (Luiz Carlos)' },
      { label: 'Iluminação', value: 'Alcides Luiz Rodrigues' },
      { label: 'Realização', value: 'Ratimbum Produções de Artes' },
    ],
    note: null,
    accessibility: [],
    image: cover('dona-rua-gentileza.png', 'dona'),
  },
  {
    id: 'saga',
    title: 'SAGA — Uma História do Povo Preto',
    strand: 'mostra-oficial',
    startsAt: '2024-10-18T19:30:00-03:00',
    durationInMinutes: 60,
    venueId: 'casa',
    company: 'Preqaria Cia de Teatro',
    stateCode: 'MG',
    author: 'Nathan Brits e João Valadares',
    director: 'Nathan Brits e João Valadares',
    rating: 'livre',
    release:
      'Traz uma narrativa possível para a trajetória do negro africano, partindo de uma de suas cosmovisões até o Brasil de hoje, misturando aspectos históricos, mitológicos e culturais. Apesar do tema sério, a peça traz leveza, como na versão do grupo para a história de Ananse, a entidade Aranha da África Central. Um diferencial do espetáculo é tratar um tema sério como o racismo estrutural no Brasil também para o público infanto-juvenil: a peça já foi vista por mais de 5 mil crianças a partir de 6 anos de idade.',
    technicalSheet: [
      { label: 'Concepção e atuação', value: 'Nathan Brits e João Valadares' },
      { label: 'Iluminação', value: 'Iasmin Duarte' },
      { label: 'Realização', value: 'Preqaria Cia de Teatro' },
    ],
    note: null,
    accessibility: [],
    image: cover('saga-povo-preto.png', 'saga'),
  },
  {
    id: 'homembanda',
    title: 'Homem Banda, O Show',
    strand: 'mostra-oficial',
    startsAt: '2024-10-19T10:00:00-03:00',
    durationInMinutes: 30,
    venueId: 'praca',
    company: 'Companhia OsViajero',
    stateCode: 'ES',
    author: 'André Forecchi',
    director: 'André Forecchi',
    rating: 'livre',
    release:
      'André é um jovem sonhador que, confrontado com o vazio de um mundo cheio de facilidades superficiais, escolhe uma vida de desafios. A busca pela felicidade através das coisas difíceis leva o personagem a um modo único de fazer música: ele cria uma geringonça que permite tocar saxofone e toda sorte de percussões simultaneamente através de cordas e roldanas sem ajuda tecnológica. Cada gesto, uma nota; cada passo, uma melodia.',
    technicalSheet: [
      { label: 'Artista solista', value: 'André Forecchi' },
      { label: 'Dramaturgia', value: 'Henrique Fontes e André Forecchi' },
      { label: 'Direção técnica', value: 'Gabriel Bebici' },
      { label: 'Direção musical', value: 'André Forecchi e Santiago Moreno' },
      { label: 'Direção de arte', value: 'Thila Paixão' },
      { label: 'Preparadora vocal e de elenco', value: 'Luciene Camargo' },
      { label: 'Produção', value: 'Karolyna Coutinho' },
    ],
    note: null,
    accessibility: [],
    image: cover('homem-banda.png', 'homembanda'),
  },
  {
    id: 'metamorfose',
    title: 'A Metamorfose',
    strand: 'mostra-oficial',
    startsAt: '2024-10-19T19:30:00-03:00',
    durationInMinutes: 50,
    venueId: 'casa',
    company: 'Grupo Anônimos de Teatro',
    stateCode: 'ES',
    author: 'Fernando Marques (adaptação do texto homônimo de Franz Kafka)',
    director: 'Ivna Messina',
    rating: 'livre',
    release:
      'Um homem desperta de sonhos intranquilos metamorfoseado num inseto monstruoso. Assim era visto por sua família. Assim era visto pelo gerente do trabalho. Pela empregada, pelos inquilinos que ocupam sua casa, pelo mundo. Neste espetáculo — um solo — conta-se a sua história; o corpo reage, a situação se instala: quem realmente se metamorfoseia enquanto o tempo passa?',
    technicalSheet: [
      { label: 'Direção', value: 'Ivna Messina' },
      { label: 'Dramaturgia', value: 'Fernando Marques' },
      { label: 'Intérprete', value: 'Luiz Carlos Cardoso' },
      { label: 'Trilha sonora', value: 'Alessandra Biato e João de Paula Junior' },
      { label: 'Cenário e figurino', value: 'Antonio Apolinário' },
      { label: 'Iluminação', value: 'Daniel Boone' },
      { label: 'Identidade visual e fotografias', value: 'Farley José' },
      { label: 'Direção de produção', value: 'Luiz Carlos Cardoso' },
      { label: 'Realização', value: 'Grupo Anônimos de Teatro' },
    ],
    note: null,
    accessibility: [],
    image: cover('a-metamorfose.png', 'metamorfose'),
  },
  {
    id: 'carambolas',
    title: 'Carambolas — Algumas Verdades Em Memória de Dona Santa',
    strand: 'mostra-oficial',
    startsAt: '2024-10-19T20:00:00-03:00',
    durationInMinutes: 50,
    venueId: 'ma',
    company: 'Repertório Artes Cênicas e Cia',
    stateCode: 'ES',
    author: 'Thalia Peçanha',
    director: 'Nieve Matos',
    rating: '16',
    release:
      'No espetáculo somos transportados para Nova Esperança, uma cidadezinha à sombra de uma grande fábrica de celulose. Mas poderia ser qualquer distrito do Espírito Santo vizinho dos portos ou siderúrgicas do estado. Inspirado na vida e morte de Dona Santa, mãe da autora Thalia Peçanha, “Carambolas” tece personagens e fatos reais à ficção, convidando todos a refletirem sobre questões urgentes de justiça social e dignidade humana.',
    technicalSheet: [
      { label: 'Direção', value: 'Nieve Matos' },
      { label: 'Dramaturgia', value: 'Thalia Peçanha e Nieve Matos' },
      {
        label: 'Elenco',
        value: 'Antônio Apolinário, Brab Joá, Léia Rodrigues, Marina Malafaia, Winny Rocha',
      },
      { label: 'Produção e assistência de direção', value: 'Erica Vilhena' },
      { label: 'Direção musical', value: 'Nataly Volcati' },
      { label: 'Direção de arte', value: 'Antônio Apolinário' },
      { label: 'Design', value: 'Alê Pin' },
      { label: 'Concepção da iluminação', value: 'André Stefson' },
      { label: 'Operação da iluminação', value: 'Mariana Rodrigues' },
      { label: 'Registro', value: 'Brunela Negreiros e Marianna Eilert' },
      { label: 'Realização', value: 'Repertório Artes Cênicas e Cia · Coletivo Elas Tramam' },
    ],
    note: null,
    accessibility: [],
    image: cover('carambolas.png', 'carambolas'),
  },
  {
    id: 'kala',
    title: 'A Maldição e o Mistério de Kalá, Uma Fábula Contemporânea',
    strand: 'mostra-oficial',
    startsAt: '2024-10-20T19:30:00-03:00',
    durationInMinutes: 50,
    venueId: 'casa',
    company: 'Grupo Rerigtiba',
    stateCode: 'ES',
    author: 'Tiche Vianna',
    director: 'Tiche Vianna',
    rating: 'livre',
    release:
      'Nelayan e Timur são dois amigos que permaneceram na Vila de Kalá depois de uma terrível maldição. Tempos depois, chega à Vila a jovem MasaDepan. O encontro de Timur e Nelayan com MasaDepan traz aos amigos a memória de Wanita e o mistério de sua partida de Kalá, há muito tempo. Desde então, Timur tenta encontrar um meio de quebrar a maldição.',
    technicalSheet: [
      { label: 'Dramaturgia e direção', value: 'Tiche Vianna' },
      { label: 'Elenco', value: 'Julia Campos, Sara Lyra, Welida Pontes e Bruno Meneguelli' },
      { label: 'Cenografia e figurino', value: 'Carlos Alberto Nunes' },
      { label: 'Assistente de cenografia e adereços', value: 'Mimo Vasco e Sara Lyra' },
      { label: 'Confecção de figurino', value: 'Raquel Miranda' },
      { label: 'Criação de trilha sonora e direção musical', value: 'Marcelo Onofri' },
      { label: 'Música incidental', value: 'Quelóide Cerebral / Compositor: Renan Alonso' },
      { label: 'Operação de som', value: 'Danilo Curtiss' },
      { label: 'Preparação vocal', value: 'Priscila Reis' },
      { label: 'Máscaras balinesas', value: 'Acervo do Grupo Rerigtiba' },
      { label: 'Produção executiva', value: 'Telma Amaral' },
      { label: 'Realização', value: 'Grupo de Teatro Rerigtiba' },
    ],
    note: null,
    accessibility: [],
    image: cover('maldicao-kala.png', 'kala'),
  },
  {
    id: 'calunga',
    title: 'Calunga — A Princesa Que Virou Boneca',
    strand: 'mostra-paralela',
    startsAt: '2024-10-13T16:00:00-03:00',
    durationInMinutes: 45,
    venueId: 'casa',
    company: 'Mais Um Ponto, Mais Um Conto',
    stateCode: 'ES',
    author: 'Eliane Correia',
    director: 'Ronny Pires',
    rating: 'livre',
    release:
      'A princesa que virou boneca remonta a história de uma princesa destemida, Calunga, cuja jornada a leva a descobrir o verdadeiro significado da coragem, amizade e amor através da tradição oral. Sua origem celebra os vínculos ancestrais entre Brasil e África, com conexão direta entre o Maracatu e o Congo capixaba através da Lenda da Casaca.',
    technicalSheet: [
      { label: 'Elenco', value: 'Caio Pereira (Avó Iroko), Eliane Correia (Calunga)' },
      { label: 'Direção', value: 'Eliane Correia e Ronny Pires' },
      { label: 'Iluminação', value: 'Carlos Ola e Matheus Soares' },
      { label: 'Sonoplastia', value: 'Eliane Correia e Gui Vieira' },
      { label: 'Contra-regra', value: 'Rosangela Correia' },
      { label: 'Cenografia', value: 'João Batista de Moraes' },
    ],
    note: null,
    accessibility: [],
    image: cover('calunga.png', 'calunga'),
  },
  {
    id: 'divertida',
    title: 'Divertida Mente',
    strand: 'mostra-paralela',
    startsAt: '2024-10-13T17:00:00-03:00',
    durationInMinutes: 50,
    venueId: 'milson',
    company: 'Cia Peralta',
    stateCode: 'ES',
    author: 'Felipe Wotkosky',
    director: 'Felipe Wotkosky',
    rating: 'livre',
    release:
      'Uma noite repleta de diversão e surpresas com Felipe Vix, ator e hipnólogo. Felipe combina seu carisma e talento com técnicas de hipnose para criar situações hilárias e momentos inesquecíveis. Voluntários da plateia terão a chance de subir ao palco e, sob a orientação de Felipe, viver experiências inacreditáveis e cômicas em uma incrível viagem pela imaginação, sempre com respeito e cuidado.',
    technicalSheet: [
      { label: 'Ator, diretor e produtor', value: 'Felipe Vieira' },
      { label: 'Operador de som', value: 'Dilan Martins' },
      { label: 'Cinegrafista', value: 'Brendom Botelho' },
    ],
    note: null,
    accessibility: [],
    image: cover('divertida-mente.png', 'divertida'),
  },
  {
    id: 'boi',
    title: 'A História do Boi de Sol',
    strand: 'mostra-paralela',
    startsAt: '2024-10-14T15:00:00-03:00',
    durationInMinutes: 40,
    venueId: 'casa',
    company: 'Os Tião Grupo de Teatro',
    stateCode: 'ES',
    author: 'Sula Borges',
    director: 'Sula Borges',
    rating: 'livre',
    release:
      'Montanha é uma pequena cidade no extremo norte capixaba e fica pertinho dos estados da Bahia e Minas Gerais. Isso torna a cidade um caldeirão cultural com diversas influências em seu povo, sua culinária, seu sotaque e sua própria cultura. A história é extraída do livro “A História do Boi de Sol”, do autor Sula Borges de Montanha / ES.',
    technicalSheet: [
      { label: 'Direção', value: 'Sula Borges' },
      {
        label: 'Atores',
        value:
          'João Vitor Borges, Debora Borges, Aendrea Antunes, Andreia Wagmaker, Cristiano Azevedo, Marcos Martins, Cristina Costa',
      },
      { label: 'Iluminador', value: 'J. Neto Borges' },
    ],
    note: null,
    accessibility: [],
    image: cover('boi-de-sol.png', 'boi'),
  },
  {
    id: 'cabrabo',
    title: 'O Auto de Cabrabó',
    strand: 'mostra-paralela',
    startsAt: '2024-10-14T19:00:00-03:00',
    durationInMinutes: 90,
    venueId: 'casa',
    company: 'CIA T21',
    stateCode: 'ES',
    author: 'Tadeu Kunzendorff',
    director: 'Tadeu Kunzendorff',
    rating: 'livre',
    release:
      'O Auto de Cabrabó conta a história de um prefeito honesto, que cuida da cidade e dos cidadãos com muito carinho, mas ele tem um passado obscuro e quando esse passado é revelado, a cidade fica de cabeça para baixo. O Auto de Cabrabó fala de um mundo como se fosse um espelho, que devolve a cada pessoa uma reflexão dos seus atos.',
    technicalSheet: [
      { label: 'Dramaturgia / direção geral', value: 'Tadeu Kunzendorff' },
      {
        label: 'Elenco',
        value:
          'Felipe Ribeiro Lima, Maria Clara Ribeiro, Maciel de Carvalho, Renato, Sophia Nunes Dias, Anna Luísa Manni, Henrique Guimarães Oliveira, Daniela Frigeri Campos, Alan Coutinho Souza, Tâmara Sá Scaramussa, Raphael Mastrorosa Lupinari, Polyanna Barboza de Oliveira, Arthur Veronez Hombre, Bernardo de Oliveira Carneiro, Samuel Itabaiana de Carvalho Pires, Séfora Araújo Silva Neto, Fabrício Fraga, Paraguassu de Souza, Luan Alejandro Nakamura Palácios, Alana Demaria Santos, Tânia Mara dos Santos Demaria',
      },
      { label: 'Produção', value: 'Erika Mariano e Monica Carvalho' },
      { label: 'Fotografia', value: 'Erika Mariano' },
    ],
    note: null,
    accessibility: [],
    image: cover('auto-de-cabrabo.png', 'cabrabo'),
  },
  {
    id: 'couro',
    title: 'Couro de Cabra e a Promessa',
    strand: 'mostra-paralela',
    startsAt: '2024-10-15T19:30:00-03:00',
    durationInMinutes: 80,
    venueId: 'sesi',
    company: 'Trupamba Cia Teatral',
    stateCode: 'ES',
    author: 'Rodrigo Paouto',
    director: 'Rodrigo Paouto',
    rating: '14',
    release:
      'Livremente inspirado na cultura nordestina brasileira, o espetáculo conta a história de Couro de Cabra, “calango” sem eira nem beira, apaixonado por Celestina, filha única do Coronel Vitalino dos Virgulhão, mas em um conflito com nuances a lá Romeu e Julieta. Os dois não podem viver este amor, pois o Coronel jamais permitiria que sua filha se casasse com alguém tão miserável.',
    technicalSheet: [
      { label: 'Dramaturgia e direção', value: 'Rodrigo Paouto' },
      {
        label: 'Elenco',
        value:
          'Washingtton Salvador, Saulo Santiago, Bia Caçador, Ana Capucho, Luan Tessarolo, Bethânia Graunke, Wesley Reis, Melky Borges, Sulivan Alves, Dave Rafael',
      },
      { label: 'Luz', value: 'Eliane Pereira' },
      { label: 'Som', value: 'Rodrigo Paouto' },
      { label: 'Figurino e maquiagem', value: 'O Grupo' },
      { label: 'Cenário', value: 'Rodrigo Paouto' },
    ],
    note: null,
    accessibility: [],
    image: cover('couro-de-cabra.png', 'couro'),
  },
  {
    id: 'avarento',
    title: 'O Avarento',
    strand: 'mostra-paralela',
    startsAt: '2024-10-19T19:30:00-03:00',
    durationInMinutes: 60,
    venueId: 'ufes',
    company: 'Grupo de Teatro Arte Oficina',
    stateCode: 'ES',
    author: 'Molière',
    director: 'Abel Santana',
    rating: 'livre',
    release:
      'Harpagão é um homem de avareza cruel e desumana, incapaz de qualquer forma de amor. A felicidade dos filhos não lhe interessa, e chega ao ponto de querer casá-los apenas para aumentar sua fortuna. Dono de vários imóveis no Condado de Big Field, explora os moradores da região cobrando aluguéis exorbitantes. Todos o odeiam e querem vê-lo morto.',
    technicalSheet: [
      { label: 'Texto e direção', value: 'Abel Santana, adaptação do clássico de Molière' },
      {
        label: 'Elenco',
        value:
          'Abel Santana, Danniel Machado, Manuela Peccin, Otávio Rodrigues, Luciana Britto, Deise Freitas, Lina Carneiro, Thais Rangel, Delza Marim, Lara Picallo',
      },
      { label: 'Sonoplastia', value: 'Thaís Duarte' },
      { label: 'Iluminação', value: 'Isabela Tonon' },
      { label: 'Coreografia', value: 'Lina Carneiro' },
      { label: 'Cenário e figurinos', value: 'Ângela Mendes e Sara Mendes' },
    ],
    note: null,
    accessibility: [],
    image: cover('o-avarento.png', 'avarento'),
  },
  {
    id: 'livros',
    title: 'Lançamento de Livros',
    strand: 'lancamento',
    startsAt: '2024-10-18T18:30:00-03:00',
    durationInMinutes: 90,
    venueId: 'milson',
    company: 'Duílio Kuster Cid, Erlon José Paschoal, Nieve Matos e autores parceiros',
    stateCode: 'ES',
    author: null,
    director: null,
    rating: 'livre',
    release:
      'Três lançamentos reunidos: “Melhor Manter o Escuro Aceso”, de Duílio Kuster Cid, coletânea de quatro textos teatrais escritos pelo ator e dramaturgo; “O Céu é o Limite”, de Erlon José Paschoal, texto teatral envolvente, sarcástico e crítico; e “Ontem, Hoje e Amanhã — Narrativas Capixabas”, de Nieve Matos e autores parceiros, coletânea de quatro dramaturgias criadas em processos colaborativos junto ao grupo Repertório Artes Cênicas e ao Instituto Cultural Tambor de Raiz.',
    technicalSheet: [
      {
        label: 'Autores',
        value: 'Duílio Kuster Cid, Erlon José Paschoal, Nieve Matos e autores parceiros',
      },
      { label: 'Local', value: 'Casa da Música Sônia Cabral — Sala Milson Henriques' },
    ],
    note: null,
    accessibility: [],
    image: null,
  },
];

/** A atividade de um id, ou `undefined` quando o id não existe. */
export function findActivity(id: string): FestivalActivity | undefined {
  return activities.find((activity) => activity.id === id);
}
